apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: https-upstream
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "kong"
proxy:
  protocol: https
route:
  protocols: 
  - https
  strip_path: false