apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
  namespace: argocd
data:
  # client-id is 'argo-workflows-sso'
  client-id: xxx
  # client-secret is 'MY-SECRET-STRING-CAN-BE-UUID'
  client-secret: xxx